### ISSUE TITLE
Prepare test case to simulate race car nose region using sample/sphere-example as reference

### ISSUE THREAD

**Issue by acrlakshman** [exaslate-research/sakthi-racing-simulation#1]
@Blesscin 
@SubhitshaManikandan 
@mxnojkumar

**Comment by Blesscin** [comment]
![image](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/b1701f9b-712f-403b-9b95-3c36d38a0ed1)
I have done all things which you have mentioned in the sample case sir, what is the next process ?

**Comment by acrlakshman** [comment]
@Blesscin 

What you have done?
* You ran the sphere-example case that I prepared and got it to run successfully.

What you need to do?
* Post-process your results and post paraview visuals in here.
* Make a copy of sphere-example case, and replace "sphere.obj" with "race car nose" geometry and redo all the steps, so that you have the visuals for race car nose geometry.
  * **_This point is the actual objective of this task._**

**Comment by Blesscin** [comment]
OK sir let us try to the visualize the results

**Comment by Blesscin** [comment]
![image](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/1956691c-47ed-4ba6-88ef-09fc4f12d7d2)
Almost done everything sir,but in paraview i cant able to fix the nose in Box sir, i have tried to change the dimensions but it didn't worked out

**Comment by acrlakshman** [comment]
Please share your test case here as a compressed file for me to take a look at it. I need to see `blockMeshDict`, `snappyHexMeshDict`, `surfaceFileExtract...`, `nose_cone.stl` or `nose_cone.obj` files. If possible all files of the test case.

@Blesscin @SubhitshaManikandan @mxnojkumar @SubhitshaManikandan @kummi0402

**Comment by Blesscin** [comment]
![image](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/84cdeea7-f92c-40ed-b27c-79199283f44a)

**Comment by Blesscin** [comment]
Real time Ground clearance of the vehicle is around 100mm and speed we can assume it as 100km/hr, How to find the reynold number sir ?

**Comment by acrlakshman** [comment]
> Real time Ground clearance of the vehicle is around 100mm and speed we can assume it as 100km/hr, How to find the reynold number sir ?

@Blesscin 

`Re = density * velocity * length scale / (dynamic viscosity)`

In this case, you can use
* density = 1.29 kg/m^3 (density of air)
* velocity = 100 * 1000 / 3600 m/s
* length scale = in this case, choose length of the nose cone i.e. along Y axis in your geometry, for your initial estimations
* dynamic viscosity = 1.8x10^-5 N-s/m^2 (of air)

Using above values, please do the calculation.

**Comment by Blesscin** [comment]
![WhatsApp Image 2024-03-25 at 9 58 59 PM](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/2fdc455f-a9c5-440e-83f1-008faf77968a)
Found the reynold number using the above mentioned formula sir, from i found this is a turbulence model because reynolds number is > 2000

**Comment by Blesscin** [comment]
![WhatsApp Image 2024-03-27 at 11 13 52 AM(1)](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/33b7932b-c530-4182-80e7-f2b1a463fd92)
![WhatsApp Image 2024-03-27 at 11 13 52 AM](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/f8d7ee5e-8327-45b3-821c-6d861fa6f6c7)
1) Bottom most coordinates point which is closes to ground : X = 0,Y = -250.091,Z = 108.97
2) Length = 1038.10mm, Width = 624.35mm, Height =500.18mm
3)Centroid of nose coordinates : X = 0,Y = 0,Z = 0

**Comment by Blesscin** [comment]
![image](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/67147441-06a8-4340-895e-9d59e69a006c)
![WhatsApp Image 2024-03-28 at 1 26 20 AM](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/ae064323-5a57-4480-8553-a02e1c81ef16)
![WhatsApp Image 2024-03-28 at 1 25 24 AM](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/0801527a-430f-4b02-ae91-fded765cdb9d)
![image](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/17d55e03-1a3f-4af8-b8f0-7ac8a8a5ae70)
sir i have made a sketch of the enclosure Box in solidworks and then i got the 8 points X Y Z coordinates from that and applied in blockMesh, the code got runned with no error but the nose is in rotated position and i cant able to fix it in center with respect to ground clearance

**Comment by acrlakshman** [comment]
@Blesscin good work so far. Before our next meeting, I want you to give it some thought on what might be causing an issue for the incorrect orientation, so that we can fix it. Please use pen and paper and analyze of what might be the change that you need to do.

**Comment by Blesscin** [comment]
![WhatsApp Image 2024-03-29 at 1 15 35 AM](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/970e1703-14db-4dc8-98e9-455713ce1771)
![WhatsApp Image 2024-03-29 at 1 15 14 AM](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/33aaa715-d5e2-434b-a5ff-f2068b8495f5)
![WhatsApp Image 2024-03-29 at 1 15 13 AM(1)](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/e7a191f8-4a89-4d73-abf8-e5168e4cb904)
![image](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/8f3bb56c-2d62-4186-bde0-c17f6fe9c102)
![image](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/50e87485-bfc1-411d-b8dd-2daffb4e5bfe)

Coordinate points got from solidworks didn't come properly sir for the configuration you have given, so myself got the coordinate points using nose dimensions which is drawn using pen and paper later i have implemented those coordinates in blockMesh & done the process, but i cant able to get correct position of nose please help me to solve this sir i been trying this for an week.

**Comment by Blesscin** [comment]
As per your request i have created a branch with guidance of kumaresh sir & for creating the boundary condition i have done many times but i cant able to make it right,after a certain period of time it makes me loosing my interest, so as per my request kindly give me a demo session to fix it & proceed further

**Comment by Blesscin** [comment]
![IMG_20240403_231941](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/e2aa2a9a-2aa9-41e2-888a-a35c10e0078c)
Boundary conditions are applied and simulated using simpleFoam

**Comment by kummi0402** [comment]
@Blesscin Thank you
Kindly report the boundary conditions implied and capture the velocity vector and pressure behavior appropriately. In this image, I couldn't able to understand the influence of air over the domain.

**Comment by Blesscin** [comment]
[Screencast from 04-04-24 08:02:36 PM IST.webm](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/73fb531f-a5a0-4171-a2d7-72e2a8dcca3b)

**Comment by acrlakshman** [comment]
@Blesscin upload the updated results you have based on today' discussion, showing velocity vectors.

**Comment by Blesscin** [comment]
![IMG_20240405_213724](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/cbd5c9de-b24d-41ae-a9fe-a175ee512c8d)
Velocity Vector results

**Comment by Blesscin** [comment]
![Screenshot from 2024-04-13 11-00-04](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/91fee6ba-c3ab-45e6-8794-cd55edb5f772)
![Screenshot from 2024-04-13 11-00-12](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/47cf9fc8-a590-4140-b106-3b53a0a595f9)
![Screenshot from 2024-04-13 11-00-21](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/17cfcfee-b6e6-4036-993c-42753574f206)
Simulation results using PisoFoam

**Comment by Blesscin** [comment]
![image](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/d475a2b6-6ad5-4804-b96f-a4837e804cc8)
![image](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/7b0082c9-9fbb-4225-9eba-8accc77f0df9)
![image](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/041ba65f-aabb-4404-a0d5-e2e72f95fafd)
![image](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/4bd1addb-6826-4d5f-9b38-0646196d1c9b)
I can able to visualize the flow (very small changes in arrow movement)sir by changing the time step values and velocity from -1 to -0.1

**Comment by Blesscin** [comment]
![Screenshot from 2024-04-29 12-45-48](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/a0019ae0-cc70-4084-acb7-3838eaf922af)
![Screenshot from 2024-04-29 12-46-03](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/9c25f995-07e5-4e68-9e6b-c9d01acd2bb7)
![Screenshot from 2024-04-29 12-46-28](https://github.com/exaslate-research/sakthi-racing-simulation/assets/144221230/ce9840c2-338b-436b-b570-a895e79aaffd)

I have followed all the steps 
step 1:
Copy paste motor bike folder & paste in run
step 2:
controlDict: Write interval : 50,end time: 50
step 3:
LES files: controlDict: end time: 0.5,write control : adjustable, write interval: 0.005
step 4:
./Allrun 
after running i have entered the reconstructparmesh and reconstructpar in terminal and created the a.foam
but i cant able to see the object inside the boundary in paraview

**Comment by kummi0402** [comment]
Blesscin, can you attach blockMesh, surfaceFeatureExtract, and snappyHexMesh log files here ?
Check the log files, where you will find the mistake. Have you tried to do that ? because you have resolved this step long ago

**Comment by acrlakshman** [comment]
closing this, as we are creating new ones to address specific parts of the project, while we are making progress.
